# CI for code style and application tests

name: test-code
on: [push, pull_request]
jobs:
  lint-python-code:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "moonraker scripts"
          use-pylint: false
          use-pycodestyle: true
          use-flake8: false
          use-black: false
          use-mypy: true
          use-isort: false
          extra-pycodestyle-options: "--ignore=E226,E301,E302,E303,W503,W504 --max-line-length=80 --max-doc-length=80"
          extra-mypy-options: "--ignore-missing-imports --follow-imports=silent"
